enum ExceptionCode {
  USER_NOT_FOUND = "USER_NOT_FOUND ",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND ",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND ",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND ",
  VARIANCE_NOT_FOUND = "VARIANCE_NOT_FOUND ",
}

export default ExceptionCode;
